apps/articles/urls.py
from django.urls import path

from .views import (
    ArchiveView,
    FeedView,
    IndexView,
    PostDetailView,
    RecommendationsView,
    delete_post,
    like_post,
)

app_name = "articles"

urlpatterns = [
    path("", IndexView.as_view(), name="root"),
    path("feed/", FeedView.as_view(), name="feed"),
    path("archive/", ArchiveView.as_view(), name="archive"),
    path("recommendations/", RecommendationsView.as_view(), name="recommendations"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post"),
    path("post/<int:post>/like/", like_post, name="like_post"),
    path("post/<int:post>/delete/", delete_post, name="delete_post"),
]

apps/users/urls.py
from django.urls import path

from .views import (
    FollowersView,
    FollowingView,
    LoginView,
    LogoutView,
    ProfileUpdateView,
    ProfileView,
    RegisterView,
    UsersView,
    follow,
    follower,
    validate_email,
    validate_username,
    validate_password,
)

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", UsersView.as_view(), name="users"),
    path("user/<str:username>/", ProfileView.as_view(), name="profile"),
    path("user/<str:username>/followers/", FollowersView.as_view(), name="followers"),
    path("user/<str:username>/following/", FollowingView.as_view(), name="following"),
    path("profile/update/", ProfileUpdateView.as_view(), name="profile_update"),
    path("follow/<int:pk>/", follow, name="follow"),
    path("follower/<int:pk>/", follower, name="follower"),
    path("validate/email/", validate_email, name="validate_email"),
    path("validate/username/", validate_username, name="validate_username"),
    path("validate/password/", validate_password, name="validate_password"),
]

config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("", include("apps.articles.urls")),
    path("", include("apps.users.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("admin/", admin.site.urls),
        path("__debug__/", include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db.models import BooleanField, CharField, EmailField, ImageField
from random import randint, shuffle
from django.db.models.fields import DateTimeField
from django.db.models.fields.related import ManyToManyField
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from django.apps import apps
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = CharField(
        _("имя пользователя"),
        max_length=55,
        unique=True,
        error_messages={
            "unique": _("Пользователь с таким именем уже зарегистрирован.")
        },
    )
    email = EmailField(
        _("электронный адрес"),
        unique=True,
        null=True,
        blank=True,
        error_messages={
            "unique": _("Пользователь с такой электронной почтой уже зарегистрирован.")
        },
    )
    image = ImageField(_("Фото профиля"), upload_to="profile/", null=True, blank=True)
    followers = ManyToManyField("users.CustomUser", "user_followers", blank=True)
    following = ManyToManyField("users.CustomUser", "user_following", blank=True)
    is_active = BooleanField(default=False)
    is_staff = BooleanField(default=False)
    join_date = DateTimeField(auto_now_add=True)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    objects = CustomUserManager()

    class Meta:
        ordering = ("username",)

    def __str__(self) -> str:
        return self.username

    def get_followers_query(self):
        return self.followers.all()

    def get_following_query(self):
        return self.following.all()

    def get_posts(self):
        return self.Post.objects.filter(user=self, is_active=True)

    def get_feed(self):
        return self.Post.objects.filter(
            user__in=list(self.following.all()) + [self], is_active=True
        )

    def get_liked_posts(self):
        return self.Post.objects.filter(likes=self, is_active=True)

    def get_archive(self):
        return self.Post.objects.filter(user=self, is_active=False)

    def get_recommendations(self):
        liked = self.Post.objects.filter(likes=self, is_active=True)[: randint(2, 6)]
        posts = []
        for like in liked:
            for user in like.likes.all().exclude(pk=self.pk)[:5]:
                for post in self.Post.objects.filter(
                    likes=user, is_active=True
                ).exclude(likes__pk=self.pk)[: randint(2, 6)]:
                    if post not in posts:
                        posts.append(post)
        shuffle(posts)
        return posts

    def get_posts_count(self):
        return self.Post.objects.filter(user=self, is_active=True).count()

    def follow(self, user) -> dict:
        if user.is_follower(self):
            user.followers.remove(self)
            return {"message": "Подписаться", "count": user.followers.count()}
        user.followers.add(self)
        return {"message": "Отписаться", "count": user.followers.count()}

    def is_follower(self, user):
        return self.followers.filter(pk=user.pk).exists()

    @staticmethod
    def get_popular(pk: int, username: str):
        return sorted(
            CustomUser.objects.filter(username__icontains=username).exclude(pk=pk),
            key=lambda user: -user.followers.count(),
        )

    @property
    def Post(self):
        return apps.get_app_config("articles").get_model("Post")

    def get_url(self):
        return f"/user/{self.username}/"

    def get_followers_url(self):
        return f"/user/{self.username}/followers/"

    def get_following_url(self):
        return f"/user/{self.username}/following/"


@receiver(m2m_changed, sender=CustomUser.followers.through)
def followers_change(sender, instance: CustomUser, action: str, pk_set: set, **kwargs):
    if action == "post_add":
        for pk in pk_set:
            if instance.pk != pk:
                user = CustomUser.objects.get(pk=pk)
                user.following.add(instance)
    if action == "post_remove":
        for pk in pk_set:
            user = CustomUser.objects.get(pk=pk)
            user.following.remove(instance)

apps/users/forms.py
from django import forms
from django.contrib.auth import forms as auth

from .models import CustomUser


class UserCreationForm(auth.UserCreationForm):
    class Meta:
        model = CustomUser
        fields = "__all__"


class FormModel(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control custom-form"
            if field == "email":
                self.fields[field].required = True
            if field == "password1" or field == "password2":
                self.fields[field].help_text = None


class UserChangeForm(FormModel):
    class Meta:
        model = CustomUser
        fields = ("username", "email", "image")


class LoginForm(auth.AuthenticationForm, FormModel):
    class Meta:
        model = CustomUser
        fields = ("username", "password")


class RegisterForm(auth.UserCreationForm, FormModel):
    class Meta:
        model = CustomUser
        fields = ("email", "username", "password1", "password2")

apps/users/views.py
import string

from django.contrib.auth.password_validation import (
    validate_password as ValidatePassword,
)
from django.contrib.auth.views import LoginView, LogoutView
from django.core.exceptions import ValidationError
from django.core.validators import validate_email as ValidateEmail
from django.http.response import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls.base import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from apps.articles.forms import PostCreate
from apps.articles.models import Post
from apps.users.mixins import RedirectAuthUser
from apps.users.models import CustomUser

from .forms import LoginForm, RegisterForm, UserChangeForm


class LoginView(RedirectAuthUser, LoginView):
    template_name = "users/login.html"
    form_class = LoginForm
    success_url = reverse_lazy("articles:feed")

    def get_redirect_url(self) -> str:
        return self.success_url


class RegisterView(RedirectAuthUser, CreateView):
    template_name = "users/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy("articles:login")

    def get_redirect_url(self) -> str:
        return self.success_url


class LogoutView(LogoutView):
    next_page = reverse_lazy("users:login")


class ProfileView(DetailView, FormView):
    model = CustomUser
    form_class = PostCreate
    template_name = "users/profile.html"

    def get_object(self):
        if self.request.user.username == self.kwargs.get("username"):
            return self.request.user
        return get_object_or_404(CustomUser, is_active=True, *self.args, **self.kwargs)

    def get_context_data(self, *args, **kwargs):
        kwargs["posts"] = kwargs["object"].get_posts()
        return super().get_context_data(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        Post.objects.create(user=request.user, text=form.data.get("text"))
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self) -> str:
        return reverse(
            "users:profile", kwargs={"username": self.kwargs.get("username")}
        )


class ProfileUpdateView(UpdateView):
    model = CustomUser
    form_class = UserChangeForm
    template_name = "users/profile_update.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self) -> str:
        return reverse("users:profile", args=[self.request.user.username])


class FollowersView(ListView):
    template_name = "users/followers.html"

    def get_queryset(self):
        if self.request.user.username == self.kwargs.get("username"):
            return self.request.user.get_followers_query()
        user = get_object_or_404(CustomUser, **self.kwargs)
        return user.get_followers_query()


class FollowingView(ListView):
    template_name = "users/following.html"

    def get_queryset(self):
        if self.request.user.username == self.kwargs.get("username"):
            return self.request.user.get_following_query()
        user = get_object_or_404(CustomUser, **self.kwargs)
        return user.get_following_query()


class UsersView(ListView):
    template_name = "users/users.html"

    def get_queryset(self):
        username = self.request.GET.get("username", "")
        return CustomUser.get_popular(self.request.user.pk, username)


def follow(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)
    return JsonResponse(request.user.follow(user))


def follower(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)
    request.user.followers.remove(user)
    return HttpResponse(None)


@csrf_exempt
def validate_email(request):
    try:
        email = request.POST.get("email", None)
        ValidateEmail(email)
    except ValidationError:
        return JsonResponse({"is_taken": True})
    else:
        response = {"is_taken": CustomUser.objects.filter(email__iexact=email).exists()}
        return JsonResponse(response)


@csrf_exempt
def validate_username(request):
    username = request.POST.get("username", None)
    for i in string.punctuation + string.whitespace:
        if i in username:
            return JsonResponse({"is_taken": True})
    response = {
        "is_taken": CustomUser.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(response)


@csrf_exempt
def validate_password(request):
    try:
        password = request.POST.get("password", None)
        ValidatePassword(password)
        return JsonResponse({"valid": True})
    except (ValidationError, TypeError):
        return JsonResponse({"valid": False})

apps/users/templates/users/followers.html
{% extends 'base.html' %}
{% load customtags %}

{% block title %}
    Подписчики {{ request.resolver_match.kwargs.username }}
{% endblock title %}

{% block header %}
    {% include 'includes/header.html' %}
{% endblock header %}

{% block content %}
    {% for object in object_list %}
        <div class="user-list">
            <a href="{{ object.get_url }}">
                <img src="{{ object.image|user_img }}" />
            </a>
            <div class="row">
                <div class="col-10"><a href="{{ object.get_url }}" class="username">@{{ object }}</a></div>
                {% if request.user.username == request.resolver_match.kwargs.username %}
                    <div class="col-2"><a href="#" class="btn-dark" user="{{ object.pk }}">Отписать</a></div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock content %}

{% block javascript %}
<script>
    $(document).on('click', '.btn-dark', function (e) {
        e.preventDefault()
        const id = $(this).attr('user')
        axios.get(`/follower/${id}/`).then(function (response) {})
        $(this).parent().parent().parent().remove();
    })
</script>
{% endblock javascript %}

apps/users/templates/users/following.html
{% extends 'base.html' %}
{% load customtags %}

{% block title %}
    Подписки {{ request.resolver_match.kwargs.username }}
{% endblock title %}

{% block content %}
    {% for object in object_list %}
        <div class="user-list">
            <a href="{{ object.get_url }}">
                <img src="{{ object.image|user_img }}" />
            </a>
            <div class="row">
                <div class="col-10"><a href="{{ object.get_url }}" class="username">@{{ object }}</a></div>
                {% if request.user.username == request.resolver_match.kwargs.username %}
                    <div class="col-2"><a href="#" class="btn-dark" user="{{ object.pk }}">Отписаться</a></div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock content %}

{% block javascript %}
<script>
    $(document).on('click', '.btn-dark', function (e) {
        e.preventDefault()
        const id = $(this).attr('user')
        axios.get(`/follow/${id}/`).then(function (response) {})
        $(this).parent().parent().parent().remove();
    })
</script>
{% endblock javascript %}

apps/users/templates/users/login.html
{% extends 'base.html' %}
{% block title %}
  Войти
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col-8 col-md-6 login-form">
            <form method="post">
            <h3 class="text-center mb-4">Авторизация</h3>
                {% csrf_token %}
                {{ form.as_p }}
                <a href="{% url 'users:register' %}">Регистрация</a>
                <button type="submit" class="btn btn-dark" disabled>Войти</button>
            </form>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
<script>
    $(document).ready(function () {
        function isEmpty() {
            if ($('#id_username').val() && $('#id_password').val()) {
                $("button[type='submit']").prop('disabled', false);
            } else {
                $("button[type='submit']").prop('disabled', true);
            }
        }
        $('#id_username').keyup(function () {
            isEmpty()
        });
        $('#id_password').keyup(function () {
            isEmpty()
        });
    })
</script>
{% endblock javascript %}

apps/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
	<link href="{% static 'css/profile.css' %}" rel="stylesheet" />
{% endblock css %}
{% load customtags %}

{% block title %}
	{{ object }}
{% endblock title %}

{% block content %}

<div class="profile">
	<div class="row">
		<div class="profile-info">
			<img src="{{ object.image|user_img }}" />
			<a href="{{ object.get_url }}" class="profile-stats">@{{ object }}</a>
			<ul class="profile-stats">
				<li><a href="{{ object.get_followers_url }}"><span id="followers">{{ object.followers.count }}</span> followers</a></li>
				<li><a href="{{ object.get_following_url }}"><span id="following">{{ object.following.count }}</span> following</a></li>
				<li><span>{{ object.get_posts_count }}</span> posts</li>
			</ul>
			{% if object.pk != request.user.pk %}
				{% if object|is_follower:request.user %}
					<a href="#" class="btn-dark" id="follow" user="{{ object.pk }}">Отписаться</a>
				{% else %}
					<a href="#" class="btn-dark" id="follow" user="{{ object.pk }}">Подписаться</a>
				{% endif %}
			{% else %}
				<a href="{% url 'users:profile_update' %}" class="btn-dark ml-4">Изменить профиль</a><br/>
				<a href="{% url 'articles:archive' %}" class="btn-dark ml-4">Архив</a>
			{% endif %}
		</div>
		<div class="profile-data pt-4 pb-4">
			{% if request.user == object %}
            <form method="post" id="post_create" class="mb-4">
				{% csrf_token %}
				<div class="input-group mb-3">
					<textarea name="text" cols="40" rows="10" class="form-control" required="" id="id_text"></textarea>
					<button type="submit" class="btn btn-secondary">Написать</button>
				</div>
            </form>
			{% endif %}
			{% include "articles/includes/post.html" %}
		</div>
	</div>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/like.js' %}"></script>
<script>
	{% if request.user.is_authenticated %}
		$('#follow').click(function () {
			const id = '{{ object.pk }}'
			axios.get(`/follow/${id}/`).then(function (response) {
				$('#followers').text(response.data.count)
				$('#follow').text(response.data.message);
			})
		})
	{% else %}
		$('#follow').click(function () {
			window.location = '/login/?next=' + window.location.pathname
		})
	{% endif %}
	
</script>
{% endblock javascript %}

apps/users/templates/users/profile_update.html
{% extends 'base.html' %}
{% block title %}
    Редактировать профиль
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col-8 col-md-6 login-form">
            <form method="post" enctype="multipart/form-data">
            <h3 class="text-center mb-4">Редактировать профиль</h3>
                {% csrf_token %}
                <p><label for="id_username">Имя пользователя:</label> <input type="text" name="username" value="admin" maxlength="55" class="form-control custom-form" required="" id="id_username"></p>
                <p><label for="id_email">Электронный адрес:</label> <input type="email" name="email" value="admin@mail.com" maxlength="254" class="form-control custom-form" required="" id="id_email"></p>
                <div class="input-group">
                    <input type="file" name="image" accept="image/*" id="id_image" class="form-control">
                    <div class="input-group-text">
                        <input class="form-check-input mt-0" type="checkbox" name="image-clear" id="image-clear_id">
                    </div>
                </div>
                <button type="submit" class="btn btn-dark mt-4">Сохранить</button>
            </form>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
{% endblock javascript %}

apps/users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Регистрация
{% endblock title %}


{% block content %}
<div class="row">
    <div class="col-8 col-md-6 login-form">
        <form method="post" id="form">
            <h3 class="text-center mb-4">Регистрация</h3>
            {% csrf_token %}
            {{ form.as_p }}
            <a href="{% url 'users:login' %}">Войти</a>
            <button type="submit" class="btn btn-dark" id="submit" disabled>Зарегистрироваться</button>
        </form>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/register.js' %}"></script>
{% endblock javascript %}

apps/users/templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
	<link href="{% static 'css/profile.css' %}" rel="stylesheet" />
{% endblock css %}
{% load customtags %}

{% block title %}
	{{ object }} | Django articles
{% endblock title %}

{% block content %}

<div class="profile">
	<div class="row">
		<div class="profile-info">
			<img src="{{ object.image|user_img }}" />
			<a href="{{ object.get_url }}" class="profile-stats">@{{ object }}</a>
			<ul class="profile-stats">
				<li>{{ object.followers }} followers</li>
				<li>{{ object.following }} following</li>
				<li>{{ object.posts }} posts</li>
			</ul>
		</div>
		<div class="profile-data">
		{% for post in posts %}
			<div class="post">
				<hr>
				<h1>{{ post.user }}</h1>
				<p>{{ post.text }}</p>
			</div>
		{% endfor %}
		</div>
	</div>
</div>
{% endblock content %}

apps/users/templates/users/users.html
{% extends 'base.html' %}
{% load customtags %}

{% block title %}
    Пользователи
{% endblock title %}

{% block content %}
    <div class="user-list">
        <div class="row">
            <div class="col-10 col-md-10" style="margin: 0 auto;">
                <form action="" method="get" class="custom-form">
                    <div class="input-group mt-3 mb-3">
                        <input type="text" class="form-control" name="username" placeholder="Имя пользователя">
                        <button type="submit" class="btn btn-secondary">Найти</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% for object in object_list %}
        <div class="user-list">
            <a href="{{ object.get_url }}">
                <img src="{{ object.image|user_img }}" />
            </a>
            <div class="row">
                <div class="col-10"><a href="{{ object.get_url }}" class="username">@{{ object }}</a></div>
                <div class="col-2">
                    {% if object|is_follower:request.user %}
                        <a href="#" class="btn-dark" id="{{ object.pk }}">Отписаться</a>
                    {% else %}
                        <a href="#" class="btn-dark" id="{{ object.pk }}">Подписаться</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

{% block javascript %}
<script>
    $(document).on('click', '.btn-dark', function (e) {
        e.preventDefault()
        const id = $(this).attr('id')
        axios.get(`/follow/${id}/`).then(function (response) {
            $('#' + id).text(response.data.message)
        })
    })
</script>
{% endblock javascript %}