apps/articles/urls.py
from django.urls import path

from .views import (
    ArchiveView,
    FeedView,
    IndexView,
    PostDetailView,
    RecommendationsView,
    delete_post,
    like_post,
)

app_name = "articles"

urlpatterns = [
    path("", IndexView.as_view(), name="root"),
    path("feed/", FeedView.as_view(), name="feed"),
    path("archive/", ArchiveView.as_view(), name="archive"),
    path("recommendations/", RecommendationsView.as_view(), name="recommendations"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post"),
    path("post/<int:post>/like/", like_post, name="like_post"),
    path("post/<int:post>/delete/", delete_post, name="delete_post"),
]

apps/users/urls.py
from django.urls import path

from .views import (
    FollowersView,
    FollowingView,
    LoginView,
    LogoutView,
    ProfileUpdateView,
    ProfileView,
    RegisterView,
    UsersView,
    follow,
    follower,
    validate_email,
    validate_username,
    validate_password,
)

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", UsersView.as_view(), name="users"),
    path("user/<str:username>/", ProfileView.as_view(), name="profile"),
    path("user/<str:username>/followers/", FollowersView.as_view(), name="followers"),
    path("user/<str:username>/following/", FollowingView.as_view(), name="following"),
    path("profile/update/", ProfileUpdateView.as_view(), name="profile_update"),
    path("follow/<int:pk>/", follow, name="follow"),
    path("follower/<int:pk>/", follower, name="follower"),
    path("validate/email/", validate_email, name="validate_email"),
    path("validate/username/", validate_username, name="validate_username"),
    path("validate/password/", validate_password, name="validate_password"),
]

config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("", include("apps.articles.urls")),
    path("", include("apps.users.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("admin/", admin.site.urls),
        path("__debug__/", include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
{% load customtags %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'articles:feed' %}">Django Articles</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link {% if request.resolver_match.url_name == 'feed' %}active{% endif %}"
            aria-current="page"
            href="{% url 'articles:feed' %}"
            >Лента</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link {% if request.resolver_match.url_name == 'recommendations' %}active{% endif %}"
            aria-current="page"
            href="{% url 'articles:recommendations' %}"
            >Рекомендации</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link {% if request.resolver_match.url_name == 'users' %}active{% endif %}"
            aria-current="page"
            href="{% url 'users:users' %}"
            >Пользователи</a
          >
        </li>
      </ul>
      {% if request.user.is_authenticated %}
        <a href="{{ request.user.get_url }}">
          <img class="header-photo" src="{{ request.user.image|user_img }}" />
        </a>
        <a class="btn btn-outline-light" href="{% url 'users:logout' %}">Выйти</a>
      {% else %}
        <a class="btn btn-outline-light" href="{% url 'users:login' %}">Войти</a>
      {% endif %}
    </div>
  </div>
</nav>